# Generated by Django 5.0.1 on 2024-03-16 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ObservedPost",
        ),
    ]
